### ISSUE TITLE
Can you show an example?

### ISSUE THREAD

**Issue by JakkuSakura** [bmhenry/ansi4tui#1]
I always have a lifetime issue constructing a Paragraph with a String. It's not useful if it can only consume leaked bytes or so.
```rust
let logs: String = String::from("hello");
let logs = ansi4tui::bytes_to_text(logs);
let messages = Paragraph::new(logs);
```
```log
error[E0277]: the trait bound `Text<'_>: From<tui::text::Text<'_>>` is not satisfied
  --> project/src/tui/bin.rs:68:28
   |
68 | ...   let messages = Paragraph::new(logs).block(Block::default().borders(Borders::TOP | Borders::LEFT | Borders::RIGHT).title("Messages"));
   |                      ^^^^^^^^^^^^^^ the trait `From<tui::text::Text<'_>>` is not implemented for `Text<'_>`
   | 
  ::: /home/jack/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/tui-0.14.0/src/widgets/paragraph.rs:97:12
   |
97 |         T: Into<Text<'a>>,
   |            -------------- required by this bound in `Paragraph::<'a>::new`
   |
   = help: the following implementations were found:
             <Text<'a> as From<&'a str>>
             <Text<'a> as From<Span<'a>>>
             <Text<'a> as From<Spans<'a>>>
             <Text<'a> as From<String>>
             <Text<'a> as From<Vec<Spans<'a>>>>
   = note: required because of the requirements on the impl of `Into<Text<'_>>` for `tui::text::Text<'_>`

```

**Comment by bmhenry** [comment]
@qiujiangkun I've added an example. you can run it with `cargo run --example simple` or just view the file to see usage.

That said, the three line example you wrote above worked fine for me.

I replaced the `Command` bytes in the example with this, and it ran just fine:
```rust
let msg = String::from("hello");
let text = ansi4tui::bytes_to_text(msg);
let paragraph = Paragraph::new(text)
    .style(Style::default())
    .block(Block::default().title("Preview").borders(Borders::ALL));
```

Maybe I'm misunderstanding the question?

Your issue may be with the way `tui-rs` handles lifetimes rather than with this library. `Paragraph`, `Text`, etc. all reference a `Cow<str>` under the hood, they don't actually "own" the data you give them. So whatever data you pass to them, make sure that data lives until the widget has been rendered or you'll run into the lifetime issues you mentioned.

**Comment by JakkuSakura** [comment]
This is weird. The same code works in your example code, but not in my code.

**Comment by JakkuSakura** [comment]
Well, I have tested out. ansi4tui does not work with `tui 0.14.0`. Here's the example code
[example.zip](https://github.com/bmhenry/ansi4tui/files/6000886/example.zip)

**Comment by bmhenry** [comment]
Tested it against the app I'm using it in, I see what you mean. Since ansi4tui exposes the `Text` struct from tui in its API, it fails to build against newer versions of tui.

I've gone ahead and just bumped the version of tui to `0.14.0` and bumped ansi4tui to `0.2.0`. So far as I can tell, there's not a better way to handle the dependency update without bumping the version of ansi4tui as well. Since the version change to tui is a minor version, it made sense to do the same here.

**Comment by JakkuSakura** [comment]
Okay, I got it and problem solved
